# Generated by Django 4.1 on 2024-09-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_remove_manual_author_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursework',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Coursework',
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='Manual',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
