# Generated by Django 4.1 on 2024-09-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_alter_discipline_name_alter_subject_discipline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
    ]
