# Generated by Django 4.1 on 2024-10-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0013_course_pdffile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='course',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursework.subject'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
