# Generated by Django 4.1 on 2024-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0014_remove_pdffile_course_pdffile_subject_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='course',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
