# Generated by Django 4.1 on 2024-10-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0016_course_semester_remove_pdffile_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursework.course'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursework.semester'),
        ),
    ]
