# Generated by Django 4.1 on 2024-10-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0017_alter_pdffile_course_alter_pdffile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursework.course'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursework.semester'),
        ),
    ]

def delete_all_pdf_files(apps, schema_editor):
    PDFFile = apps.get_model('coursework', 'PDFFile')
    PDFFile.objects.all().delete()