# Generated by Django 5.1.7 on 2025-04-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0022_alter_discipline_options_alter_pdffile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_upload_pdf', 'Разрешение на загрузку PDF файлов')], 'verbose_name': 'PDF файл', 'verbose_name_plural': 'PDF файлы'},
        ),
    ]
